- source/cart.html
- source/contact.html
- source/layout.html
- source/product.html
> Ensure any forms have accept-charset=utf8 and a hidden utf8 element

- source/checkout.html
- source/layout.html
- source/maintenance.html
- source/settings.json
> remove meta keywords/description

- source/product.html
- source/settings.json
- source/stylesheets/product.css.sass
This adds theme styling for the instant checkout button for Sidecar
> Instant checkout updates

- source/contact.html
- source/stylesheets/contact.css.sass
- source/stylesheets/layout.css.sass
Fixes https://www.pivotaltracker.com/story/show/169743515
> Properly label form inputs and restore focus style

- source/product.html
- source/stylesheets/custom.css.sass
- source/stylesheets/layout.css.sass
- source/stylesheets/product.css.sass
Fixes https://www.pivotaltracker.com/story/show/169601613
> #169601613 product contrast improvements

- source/product.html
- source/stylesheets/product.css.sass
Changes h5 to an h2 to follow the heading flow
Fixes https://www.pivotaltracker.com/story/show/169601617
> Update Product page heading

- source/product.html
Remove "Image of" in alt tag
Fixes https://www.pivotaltracker.com/story/show/169601616
> Accessible images on Product page

- source/layout.html
- source/stylesheets/layout.css.sass
- change shop title to 18px
- change height of nav to 55px
- change # font size to 14px
- change the circle height and width to 27px
- Ensure that the circle is centered within the nav height
Fixes https://www.pivotaltracker.com/story/show/169953626
> Mobile nav: Update contrast to meet minimum requirements

- source/stylesheets/layout.css.sass
- source/stylesheets/product.css.sass
Fixes https://www.pivotaltracker.com/story/show/169601613
> Improve product page contrast

- source/stylesheets/contact.css.sass
Fixes https://www.pivotaltracker.com/story/show/170001254
> Increase font size on Contact form labels, inputs, and instructions

- source/cart.html
Screen reader was reading this as "times" instead of "Remove item"
Fixes https://www.pivotaltracker.com/story/show/169826520
> Change button title to aria-label

- source/stylesheets/product.css.sass
Fixes https://www.pivotaltracker.com/story/show/170006883
> Remove removal of bottom margin on Product page title

- source/stylesheets/layout.css.sass
Fixes https://www.pivotaltracker.com/story/show/170115056
> Increase error text size

- source/layout.html
- source/settings.json
- source/stylesheets/layout.css.sass
Fixes https://www.pivotaltracker.com/story/show/170090095
> Constrain header image properly

- source/layout.html
- source/product.html
- source/settings.json
- source/stylesheets/contact.css.sass
- source/stylesheets/layout.css.sass
- source/stylesheets/product.css.sass
Add new Powered by Big Cartel credit
Rename Option to Variant
Default style updates
Misc CSS fixes
> Misc. theme updates

- source/layout.html
> fix: Add "role" attribute to search form in layout.html

- source/contact.html
- source/javascripts/store.js
- source/layout.html
- source/settings.json
- source/stylesheets/layout.sass
- source/stylesheets/product.sass
- Remove contact form tabindexes for accessibility
- Move recaptcha note to bottom of Contact form
- Resize product page images to more reasonable width
- Add 'skip to main content' link
> v2.0.1 Updates

- source/home.html
- source/settings.json
adds theme settings for "Featured" homepage title.
> feat: "Featured" homepage title configurable in theme settings

- source/home.html
- source/product.html
- source/products.html
- source/settings.json
> feat: add setting to hide prices of sold out products

- source/home.html
- source/products.html
- source/settings.json
- source/stylesheets/custom.sass
- source/stylesheets/layout.sass
- source/stylesheets/products.sass
* feat: all products link on homepage with new setting to control text
* chore: center page titles for non product pages on mobile
* chore: increase h1 heading size from 1.5rem to 1.75rem
* chore: increase mobile header height from 72px to 80px
* chore: change default of sold out products to hide prices
> Sidecar v2.6.0

- source/home.html
- source/products.html
- source/settings.json
- source/stylesheets/layout.sass
- source/stylesheets/product.sass
- source/stylesheets/products.sass
* chore: change footer colorst o use sidebar colors
* chore: polish hover underline style on products in grid
* chore: adjust font weigth on product name and price
* chore: revert h1 heading back to 1.5rem
> Sidecar v2.6.1

- source/settings.json
- source/stylesheets/layout.sass
- fix: overcomes issues with grid items inheriting flexbox auto min width.
> Sidecar_2.12.2

- source/home.html
- source/javascripts/image-collage.js
- source/javascripts/store.js
- source/settings.json
- source/stylesheets/home.sass
- source/stylesheets/layout.sass
- source/stylesheets/products.sass
- source/theme.js
- feat: homepage featured categories support with category collage option
- chore: decrease product grid text size on mobile
- chore: decrease h1 headings on mobile
> Sidecar v2.14.0

- source/settings.json
chore: featured categories 0 for upgrades
> Sidecar 2.14.1

- source/home.html
- source/javascripts/image-collage.js
- source/settings.json
- source/stylesheets/products.sass
- fix: correctly handle single image catgories for collages and the grid image style
- chore: use liquid pluralization filter
> Sidecar 2.14.2
